import { article } from './article';

export const ARTICLES: article[] = [
  {
    id: 0,
    title: 'Critical Update for Hack to D-Link Routers',
    content: '<p><img style="padding: 0 15px; float: left;" width="200px" src="/assets/img/d-link_dir-859.jpg" alt=""></p><p>A previous exploit was released that allows The D-Link DIR-859 Router allows. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur laoreet lorem at magna interdum, auctor aliquam diam faucibus. Integer sed velit vel nibh mattis pellentesque non sed dolor. Nunc sit amet tincidunt nisl. Morbi scelerisque, neque vitae facilisis vulputate, est mi accumsan orci, nec ultrices nunc neque nec leo. Etiam eget ante ex. Integer mi diam, aliquet et eros nec, auctor vestibulum lorem. Fusce ac pulvinar diam, a pellentesque ligula. Donec eget suscipit lorem. Fusce tempus, dui et eleifend finibus, eros elit tempor nulla, nec facilisis mauris nulla consequat magna. Phasellus euismod scelerisque enim, nec euismod lacus volutpat at. Sed sapien felis, bibendum vitae leo vel, tincidunt commodo lorem. Mauris tincidunt turpis eget nisi fringilla, non pretium ligula pretium. Duis sed neque in felis interdum condimentum eget a nunc.</p><p>Ut mattis lorem in neque mollis, sed malesuada enim interdum. Nunc pellentesque lectus nec dictum elementum. Nulla nec nibh eget augue pharetra iaculis. Maecenas convallis orci diam, id molestie lorem pellentesque eget. Curabitur porttitor ex ut rutrum auctor. Proin at auctor leo. Aliquam pulvinar vehicula tellus at finibus. Donec sed ornare eros. Morbi volutpat tempus libero ut pretium. Aenean eget dictum enim, at commodo mauris. Quisque tristique rhoncus consectetur. Phasellus maximus fringilla congue.<p></p>Duis varius, ipsum in convallis fringilla, lacus purus convallis elit, non sollicitudin lorem massa ac lectus. Aliquam felis felis, pharetra quis leo eget, egestas pellentesque purus. Vestibulum est eros, euismod vitae arcu quis, venenatis interdum erat. Pellentesque malesuada convallis tellus, id malesuada lectus lobortis ut. Vestibulum nec tempus nunc. In non elit sapien. Nam auctor suscipit mi eu gravida. Praesent tincidunt finibus nisi, nec faucibus turpis luctus suscipit.</p>',
    date: new Date(2019, 12, 26),
    url: "CVE-2019-20213"
  },
  {
    id: 1,
    title: 'Critical Update for Hack to D-Link Routers',
    content: '<p><img style="padding: 0 15px; float: left;" width="200px" src="/assets/img/d-link_dir-859.jpg" alt=""></p><p>A previous exploit was released that allows The D-Link DIR-859 Router allows. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur laoreet lorem at magna interdum, auctor aliquam diam faucibus. Integer sed velit vel nibh mattis pellentesque non sed dolor. Nunc sit amet tincidunt nisl. Morbi scelerisque, neque vitae facilisis vulputate, est mi accumsan orci, nec ultrices nunc neque nec leo. Etiam eget ante ex. Integer mi diam, aliquet et eros nec, auctor vestibulum lorem. Fusce ac pulvinar diam, a pellentesque ligula. Donec eget suscipit lorem. Fusce tempus, dui et eleifend finibus, eros elit tempor nulla, nec facilisis mauris nulla consequat magna. Phasellus euismod scelerisque enim, nec euismod lacus volutpat at. Sed sapien felis, bibendum vitae leo vel, tincidunt commodo lorem. Mauris tincidunt turpis eget nisi fringilla, non pretium ligula pretium. Duis sed neque in felis interdum condimentum eget a nunc.</p><p>Ut mattis lorem in neque mollis, sed malesuada enim interdum. Nunc pellentesque lectus nec dictum elementum. Nulla nec nibh eget augue pharetra iaculis. Maecenas convallis orci diam, id molestie lorem pellentesque eget. Curabitur porttitor ex ut rutrum auctor. Proin at auctor leo. Aliquam pulvinar vehicula tellus at finibus. Donec sed ornare eros. Morbi volutpat tempus libero ut pretium. Aenean eget dictum enim, at commodo mauris. Quisque tristique rhoncus consectetur. Phasellus maximus fringilla congue.<p></p>Duis varius, ipsum in convallis fringilla, lacus purus convallis elit, non sollicitudin lorem massa ac lectus. Aliquam felis felis, pharetra quis leo eget, egestas pellentesque purus. Vestibulum est eros, euismod vitae arcu quis, venenatis interdum erat. Pellentesque malesuada convallis tellus, id malesuada lectus lobortis ut. Vestibulum nec tempus nunc. In non elit sapien. Nam auctor suscipit mi eu gravida. Praesent tincidunt finibus nisi, nec faucibus turpis luctus suscipit.</p>',
    date: new Date(2019, 12, 26),
    url: "CVE-2019-20213"
  }
]